src/BookGallery/Models/API/MovieGenres.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace MovieGallery.Models.API
{

    public class MovieGenres
    {
        [JsonProperty(PropertyName = "genres")]
        public Genre[] Genres { get; set; }
    }

    public class Genre
    {
        [JsonProperty(PropertyName = "id")]
        public int Id { get; set; }

        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
    }

}

src/BookGallery/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MovieGallery.Models
{
    public class Artist
    {
        public string Name { get; set; }
        public string Role { get; set; }
    }
}

src/BookGallery/Models/BookGalleryItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.AccessControl;
using System.Web;

namespace MovieGallery.Models
{
    public class BookGalleryItem
    {
        public int Id { get; set; }
        public string SeriesTitle { get; set; }
        public int IssueNumber { get; set; }
        public string DescriptionHtml { get; set; }
        public Artist[] Artists { get; set; }
        public bool Favorite { get; set; }

        public string DisplayText => SeriesTitle + " #" + IssueNumber;

        //Images Schema: series-title-issuenumber.jpg
        public string CoverImageFileName => SeriesTitle.Replace(" ", "-").ToLower() + "-" + IssueNumber + ".jpg";
    }
}

src/BookGallery/Models/IMovieSearchItems.cs
namespace MovieGallery.Models
{
    public interface IMovieSearchItems
    {
        MovieItem[] MovieItems { get; set; }
        int page { get; set; }
        int total_pages { get; set; }
        int total_results { get; set; }
    }
}

src/BookGallery/Models/MovieDetailsItem.cs
namespace MovieGallery.Models
{

    public class MovieDetailsItem
    {
        public bool adult { get; set; }
        public string backdrop_path { get; set; }
        public object belongs_to_collection { get; set; }
        public int budget { get; set; }
        public Genre[] genres { get; set; }
        public string homepage { get; set; }
        public int id { get; set; }
        public string imdb_id { get; set; }
        public string original_language { get; set; }
        public string original_title { get; set; }
        public string overview { get; set; }
        public float popularity { get; set; }
        public string poster_path { get; set; }
        public Production_Companies[] production_companies { get; set; }
        public Production_Countries[] production_countries { get; set; }
        public string release_date { get; set; }
        
        public int runtime { get; set; }
        public Spoken_Languages[] spoken_languages { get; set; }
        public string status { get; set; }
        public string tagline { get; set; }
        public string title { get; set; }
        public bool video { get; set; }
        public float vote_average { get; set; }
        public int vote_count { get; set; }
    }

    public class Genre
    {
        public int id { get; set; }
        public string name { get; set; }
    }

    public class Production_Companies
    {
        public string name { get; set; }
        public int id { get; set; }
    }

    public class Production_Countries
    {
        public string iso_3166_1 { get; set; }
        public string name { get; set; }
    }

    public class Spoken_Languages
    {
        public string iso_639_1 { get; set; }
        public string name { get; set; }
    }

}

src/BookGallery/Models/MovieSearchItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace MovieGallery.Models
{

    public class MovieSearchItems : IMovieSearchItems
    {
        public int page { get; set; }
        public int total_results { get; set; }
        public int total_pages { get; set; }
        [JsonProperty(PropertyName = "Results")]
        public MovieItem[] MovieItems { get; set; }
    }

    public class MovieItem
    {
        public int vote_count { get; set; }
        public int id { get; set; }
        public bool video { get; set; }
        public float vote_average { get; set; }
        public string title { get; set; }
        public float popularity { get; set; }
        public string poster_path { get; set; }
        public string original_language { get; set; }
        public string original_title { get; set; }
        public int?[] genre_ids { get; set; }
        public List<string> GenreStrings { get; set; } = new List<string>();
        public string backdrop_path { get; set; }
        public bool adult { get; set; }
        public string overview { get; set; }
        public string release_date { get; set; }
    }




    

}

src/BookGallery/Models/ViewModels/SearchMovieViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MovieGallery.Data;
using MovieGallery.Models.API;

namespace MovieGallery.Models.ViewModels
{
    public class SearchMovieViewModel<T> : IMovieSearchItems
    {
        public API.Genre[] gengres { get; }
        public MovieItem[] MovieItems { get; set; }
        public int page { get; set; }
        public int total_pages { get; set; }
        public int total_results { get; set; }
       
        public SearchMovieViewModel(MovieGalleryRepository movieRepository, MovieItem[] movieItems, int page, int total_pages, int total_results)
        {
            gengres = movieRepository.MovieGenre.Genres;
            MovieItems = movieItems;
            this.page = page;
            this.total_pages = total_pages;
            this.total_results = total_results;
            MapGengresStringToPage();
        }

        public void MapGengresStringToPage()
        {
            foreach (var movie in MovieItems)
            {
                foreach (var id in movie.genre_ids)
                {
                    movie.GenreStrings.Add(gengres.FirstOrDefault(z => z.Id == id)?.Name);
                }
            }
        }
      
    }
}

src/BookGallery/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MovieGallery.Data;

namespace MovieGallery.Controllers
{
    public class HomeController : Controller
    {
   
    }
}

src/BookGallery/Controllers/MovieGalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MovieGallery.Data;
using MovieGallery.Models;
using MovieGallery.Models.ViewModels;

namespace MovieGallery.Controllers
{
    public class MovieGalleryController : Controller
    {
        

        public MovieGalleryController()
        {
           
        }

        public ActionResult Detail(int id)
        {
            if(id == 0)
            {
                return HttpNotFound();
            }
           
            var detailsAboutMovie = new MovieGalleryRepository().GetDetailsAboutMovie(id);

            return View(detailsAboutMovie);
        }
        
        public ActionResult Index()
        {
            var repo = new MovieGalleryRepository();
            var movieRepo = repo.GetMostPopularMovies();
            var viewModel = new SearchMovieViewModel<MovieSearchItems>(repo, movieRepo.MovieItems, movieRepo.page, movieRepo.total_pages, movieRepo.total_results);
            return View(viewModel);
        }

        public ActionResult LookUpMovie()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LookUpMovie(string movieToFind)
        {
            ViewBag.SearchingFor = movieToFind;
            var movieRepository = new MovieGalleryRepository();
            var movieItem = movieRepository.SearchForAMovie(movieToFind);
            var viewModel = new SearchMovieViewModel<MovieSearchItems>(movieRepository, movieItem.MovieItems, movieItem.page, movieItem.total_pages, movieItem.total_results);
            return View(viewModel);
        }
    }
}

src/BookGallery/Views/MovieGallery/Detail.cshtml
@model MovieGallery.Models.MovieDetailsItem

@{
    ViewBag.ShowBackBar = true;
}
  

<h2>@Model.title</h2>
    <div class="row">
        <div class="col-md-6">
            <div class="well">
              
                <h5><a href="http://www.imdb.com/title/@Model.imdb_id" alt="IMDB" target="_blank">IMDB</a></h5>
                <h5><label>Language:&nbsp;</label> @Model.original_language</h5>
                <h5><label>Release date:&nbsp;</label>@(Model.release_date)</h5>
                <h5>Languages:</h5>
                <div>
                    <ul>
                        @foreach (var spokenLanguage in Model.spoken_languages)
                        {
                            <li>@spokenLanguage.name</li>
                        }
                    </ul>
                </div>
            </div>
            <h5>Description:</h5>
            <div>@Html.Raw(Model.overview)</div>
        </div>
        <div class="col-md-6">
            <img src="http://image.tmdb.org/t/p/w185/@Model.poster_path"
                 alt="@Model.title" class="img-responsive"/>
        </div>
    </div>

src/BookGallery/Views/MovieGallery/Index.cshtml
@using MovieGallery.Models;
@using MovieGallery.Models.ViewModels;

@model SearchMovieViewModel<MovieSearchItems>
@{
    ViewBag.Title = "Popular Movies";
    ViewBag.SearchMovie = true;

}
<h2>Overview</h2>
<div class="row">
    @foreach (var movie in Model.MovieItems)
    {
        <div class="col-md-3">
            <a href=@Url.Action("Detail", new {id = movie.id})>
                <h4>@movie.title</h4>
                <h5><i class="fa fa-star fa-lg"></i><label>&nbsp;</label>@movie.vote_average</h5>
                <img src="http://image.tmdb.org/t/p/w185/@movie.poster_path"
                     alt="@movie.title" class="poster img-responsive" />
            </a>
        </div>
    }

</div>

src/BookGallery/Views/MovieGallery/LookUpMovie.cshtml
@using MovieGallery.Models;
@using MovieGallery.Models.ViewModels;

@model  SearchMovieViewModel<MovieSearchItems>
@{
    ViewBag.Title = "LookUpMovie";
    ViewBag.ShowBackBar = true;
    

}

        <h2>Search For Movie</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("LookUpMovie", "MovieGallery", FormMethod.Post))
            {
                <div class="well">
                    <h4>Search:</h4>
                    <input type="text" id="movieToFind" name="movieToFind"/>
                    <input class="btn-submit" type="submit" id="submitId" value="Submit" />
                    @if(ViewBag.SearchKey != null)
                    {
                        <span>
                            Search Key: @ViewBag.SearchKey +"..."
                        </span>
                    }
                </div>
            }
            @if (Model != null)
            {
            
                <h2>@(Model.MovieItems?.Length.ToString() ?? "0") hits </h2>

                if (Model.MovieItems != null)
                {
                    foreach (var movie in Model.MovieItems)
                    {
                        <div class="row row-space">
                            <div class="col-md-3">
                                <img src="http://image.tmdb.org/t/p/w185/@movie.poster_path"
                                     alt="@movie.title" class="poster img-responsive"/>
                            </div>
                            <div class="col-md-9">
                                <div class="well">

                                    <h5><label>Movie Title:&nbsp;</label>@movie.title</h5>
                                    <h5><label>Genre:&nbsp;</label>@String.Join(", ", movie.GenreStrings)</h5>
                                    <h5><label>Release Date:&nbsp;</label> @movie.release_date</h5>
                                    <h5><label>Popularity:&nbsp;</label>@movie.popularity</h5>
                                    <h5><label>Vote Average:&nbsp;</label>@movie.vote_average</h5>


                                </div>
                                <h4>Description</h4>
                                <div>@movie.overview</div>
                            </div>

                        </div>
                    }
                }
            }

        </div>
    </div>

src/BookGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Amazing Movie Gallery</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Movie Gallery", "Index", "MovieGallery", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <!-- Add menu items here -->
            </ul>
        </div>
    </div>
</div>
    
    @if (ViewBag.ShowBackBar != null && ViewBag.ShowBackBar)
    {
        <div class="backbar">
            <div class="container">
               @Html.ActionLink("Return To Overview","Index","MovieGallery", null, new{ @class = "btn btn-default" })
              
            </div>
        </div>
    }
@if (ViewBag.SearchMovie != null && ViewBag.SearchMovie)
{
    <div class="backbar">
        <div class="container">
            @Html.ActionLink("Search Movie","LookUpMovie", "MovieGallery", null, new{ @class = "btn btn-default" })
              
        </div>
    </div>
}
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Movie Gallery</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>